resolver: ./cardano-sl.yaml
packages:
- .

extra-deps:
- git: https://github.com/input-output-hk/cardano-sl
  commit: c0b87ab333bb833fc05193d1d569bf78fd4430ef
  subdirs:
    - acid-state-exts
    - binary
    - binary/test
    - chain
    - chain/test
    - client
    - core
    - core/test
    - crypto
    - crypto/test
    - db
    - infra
    - lib
    - mnemonic
    - networking
    - node-ipc
    - util
    - util/test
    - utxo
    - x509
